# Generated by Django 4.2.6 on 2023-11-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_data_shared',
            new_name='can_data_be_shared',
        ),
    ]
